### PR TITLE
30 Minutes notification message

### LINKED ISSUE #4: Create notification message 30 minutes before op start
30 minutes before the OP starts, the bot should post a message about the OP beginning in a specific game channel (possibly ping the game role). This should be done even though we utilize Discord Events since not everyone knows how to use those...

### LINKED ISSUE #31: Operations scheduled message
Enable the bot to have a configurable schedule to send game operation messages to channels.

There are different approaches we can take on this since the current config is based from a settings file:

we could enable an endpoint that updates the setting: e.g. updateGameOperationNotification(gameid, channelid,  schedule).

By doing this, we can allow external agents to modify this setting (provided they have the right credentials).
This would grant as the possibility to add a control somewhere in opserv to modify the schedule through a nice UI.

Alternatively, we could enable a command, so that through bot commands selected individuals could configure the game for the channel they are in.
E.g. !opNotifications gameId schedule

That would trigger the update to send the message for that game, on that schedule on the channel where the message is sent.

Another option would be to use the opserv db, save the configuration in there and then read periodically for updates. This would allow to work on the opserv side without exposing new endpoints, but it creates a hard dependency on an external service that is already more interconnected than it should.

### PR DESCRIPTION
**Pull request by Goltred**
This PR includes the logic related to sending the 30 minutes notification message on configured channels. This includes:
* Some refactoring of the existing message functions so that they are reusable by other pieces of the bot.
* Implementation of a simple sqlite local database to record ops that have been notified so that we don't send multiple notifications for the same thing (only for 30 minutes notif right now)

@PatrickPedersen - I'm going to need some help completing those models that we need to get user and game information since i don't know the structure of the xenforo db :)

### CODE REVIEW

**Comment by PatrickPedersen** [comment]
@Goltred If you look at these queries, you should be able to get some, if not all of the way there:
https://github.com/THE-BWC/Discord_OpServBot/blob/main/models/xenforo/xenProvider.js

Otherwise, I'll look at it later when I have more time.

**Comment by Goltred** [comment]
Yeah, no worries there's no pressure for this.

The queries do help but we might still run into issues it peewee doesn't like that I might be missing some fields in the model.

**Comment by PatrickPedersen** [comment]
@Goltred Sorry for all the pings. Technically this is now ready to merge with main. Is there anything else you want to do on this PR? Or should we just merge?

**Comment by Goltred** [comment]
Sorry, i think it should be good to go. I'm not merging without consent though so feel free to do so? :D

**Pull request merged**
